export const employees = [
  {
    id: "emp_1",
    name: "Aarav Sharma",
    email: "aarav@ethara.ai",
    password: "123456",
    team_id: null,     //for placeholder-data.ts only
    team_name: null,
    role: "admin",
    position: "Admin",
  },

  {
    id: "emp_2",
    name: "Riya Kapoor",
    email: "riya@ethara.ai",
    password: "123456",
    team_id: "team_1",     //for placeholder-data.ts only
    team_name: 'Team Alpha',
    role: "team_lead",
    position: "Senior Software Engineer",
  },
  {
    id: "emp_3",
    name: "Kunal Mehta",
    email: "kunal@ethara.ai",
    password: "123456",
    team_id: "team_1",     //for placeholder-data.ts only
    team_name: 'Team Alpha',
    role: "team_member",
    position: "Frontend Engineer",
  },
  {
    id: "emp_4",
    name: "Sneha Verma",
    email: "sneha@ethara.ai",
    password: "123456",
    team_id: "team_1",     //for placeholder-data.ts only
    team_name: 'Team Alpha',
    role: "team_member",
    position: "QA Engineer",
  },

  {
    id: "emp_5",
    name: "Aditya Singh",
    email: "aditya@ethara.ai",
    password: "123456",
    team_id: "team_2",     //for placeholder-data.ts only
    team_name: 'Team Beta',
    role: "team_lead",
    position: "Senior Software Engineer",
  },
  {
    id: "emp_6",
    name: "Priya Nair",
    email: "priya@ethara.ai",
    password: "123456",
    team_id: "team_2",     //for placeholder-data.ts only
    team_name: 'Team Beta',
    role: "team_member",
    position: "Backend Engineer",
  },
  {
    id: "emp_7",
    name: "Rahul Joshi",
    email: "rahul@ethara.ai",
    password: "123456",
    team_id: "team_2",     //for placeholder-data.ts only
    team_name: 'Team Beta',
    role: "team_member",
    position: "Backend Engineer",
  },
  {
    id: "emp_8",
    name: "Ishita Roy",
    email: "ishita@ethara.ai",
    password: "123456",
    team_id: "team_2",     //for placeholder-data.ts only
    team_name: 'Team Beta',
    role: "team_member",
    position: "Tester",
  },

  {
    id: "emp_9",
    name: "Dev Malhotra",
    email: "dev@ethara.ai",
    password: "123456",
    team_id: "team_3",
    team_name: 'Team Gamma',
    role: "team_lead",
    position: "Senior Software Engineer",
  },
  {
    id: "emp_10",
    name: "Neha Arora",
    email: "neha@ethara.ai",
    password: "123456",
    team_id: "team_3",     //for placeholder-data.ts only
    team_name: 'Team Gamma',
    role: "team_member",
    position: "Devops Engineer",
  },
  {
    id: "emp_11",
    name: "Kabir Khan",
    email: "kabir@ethara.ai",
    password: "123456",
    team_id: "team_3",     //for placeholder-data.ts only
    team_name: 'Team Gamma',
    role: "team_member",
    position: "Backend Engineer",
  },
  {
    id: "emp_12",
    name: "Ananya Das",
    email: "ananya@ethara.ai",
    password: "123456",
    team_id: "team_3",     //for placeholder-data.ts only
    team_name: 'Team Gamma',
    role: "team_member",
    position: "QA Engineer",
  },

  {
    id: "emp_13",
    name: "Yash Patel",
    email: "yash@ethara.ai",
    password: "123456",
    team_id: "team_4",     //for placeholder-data.ts only
    team_name: 'Team Delta',
    role: "team_lead",
    position: "Senior Software Engineer",
  },
  {
    id: "emp_14",
    name: "Meera Iyer",
    email: "meera@ethara.ai",
    password: "123456",
    team_id: "team_4",     //for placeholder-data.ts only
    team_name: 'Team Delta',
    role: "team_member",
    position: "Frontend Engineer",
  },
  {
    id: "emp_15",
    name: "Arjun Rao",
    email: "arjun@ethara.ai",
    password: "123456",
    team_id: "team_4",     //for placeholder-data.ts only
    team_name: 'Team Delta',
    role: "team_member",
    position: "Frontend Engineer",
  },
  {
    id: "emp_16",
    name: "Pooja Mishra",
    email: "pooja@ethara.ai",
    password: "123456",
    team_id: "team_4",     //for placeholder-data.ts only
    team_name: 'Team Delta',
    role: "team_member",
    position: "Tester",
  },

  {
    id: "emp_17",
    name: "Rohan Sethi",
    email: "rohan@ethara.ai",
    password: "123456",
    team_id: null,     //for placeholder-data.ts only
    team_name: null,
    role: "on_bench",
    position: "Backend Engineer",
  },
  {
    id: "emp_18",
    name: "Simran Gill",
    email: "simran@ethara.ai",
    password: "123456",
    team_id: null,     //for placeholder-data.ts only
    team_name: null,
    role: "on_bench",
    position: "Frontend Engineer",
  },
  {
    id: "emp_19",
    name: "Vikas Jain",
    email: "vikas@ethara.ai",
    password: "123456",
    team_id: null,     //for placeholder-data.ts only
    team_name: null,
    role: "on_bench",
    position: "Devops Engineer",
  },
  {
    id: "emp_20",
    name: "Tanya Bhatia",
    email: "tanya@ethara.ai",
    password: "123456",
    team_id: null,     //for placeholder-data.ts only
    team_name: null,
    role: "on_bench",
    position: "QA Engineer",
  },
];

export const teams = [
  {
    id: "team_1",
    name: "Team Alpha",
    open_tasks: 3,
    completed_tasks: 4,
  },

  {
    id: "team_2",
    name: "Team Beta",
    open_tasks: 5,
    completed_tasks: 2,
  },

  {
    id: "team_3",
    name: "Team Gamma",
    open_tasks: 2,
    completed_tasks: 6,
  },

  {
    id: "team_4",
    name: "Team Delta",
    open_tasks: 4,
    completed_tasks: 3,
  },

  {
    id: "team_5",
    name: "Team Epsilon",
    open_tasks: 1,
    completed_tasks: 0,
  },
];

export const projects = [
  {
    id: "proj_1",
    name: "CRM Dashboard",
    description: "Internal customer management dashboard",
    team_id: "team_1",
    team_name: "Team Alpha",
    status: "active",
    date_of_creation: "2026-04-01",
    date_of_assigning: "2026-04-03",
    deadline: "2026-06-15",
    progress: 65,
    activity_logs: [
      "Project created by Aarav Sharma on 2026-04-01",
      "Project assigned to Frontend Team on 2026-04-03",
    ],
  },

  {
    id: "proj_2",
    name: "Payment API",
    description: "Secure payment gateway APIs",
    team_id: "team_2",
    team_name: "Team Beta",
    status: "pending",
    date_of_creation: "2026-05-01",
    date_of_assigning: "2026-05-02",
    deadline: "2026-07-01",
    progress: 20,
    activity_logs: [
      "Project created by Aarav Sharma on 2026-05-01",
    ],
  },

  {
    id: "proj_3",
    name: "Cloud Migration",
    description: "Migrating services to cloud infrastructure",
    team_id: "team_3",
    team_name: "Team Gamma",
    status: "completed",
    date_of_creation: "2026-01-10",
    date_of_assigning: "2026-01-15",
    deadline: "2026-03-30",
    progress: 100,
    activity_logs: [
      "Project completed successfully on 2026-03-28",
    ],
  },

  {
    id: "proj_4",
    name: "E-Commerce Mobile App",
    description: "Cross-platform shopping application",
    team_id: "team_4",
    team_name: "Team Delta",
    status: "overdue",
    date_of_creation: "2026-02-01",
    date_of_assigning: "2026-02-05",
    deadline: "2026-04-20",
    progress: 75,
    activity_logs: [
      "Deadline exceeded on 2026-04-20",
    ],
  },

  {
    id: "proj_5",
    name: "AI Research Platform",
    description: "Research platform for internal AI tools",
    team_id: "team_5",
    team_name: "Team Epsilon",
    status: "pending",
    date_of_creation: "2026-05-08",
    date_of_assigning: null,
    deadline: "2026-09-01",
    progress: 5,
    activity_logs: [
      "Project waiting for team assignment",
    ],
  },
];

export const tasks = [
  {
    id: "task_1",
    name: "Setup dashboard layout",
    description: "Create base dashboard UI",
    project_id: "proj_1",
    assigned_emp_id: "emp_3",
    assigned_emp_email: "kunal@ethara.ai",
    date_of_creation: "2026-04-01",
    date_of_assigning: "2026-04-02",
    deadline: "2026-04-07",
    status: "completed",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-04-01",
      "Task assigned to Kunal Mehta on 2026-04-02",
      "Kunal Mehta changed task status to in progress on 2026-04-03",
      "Kunal Mehta marked task as completed on 2026-04-05",
    ],
  },

  {
    id: "task_2",
    name: "Sidebar navigation",
    description: "Build responsive sidebar",
    project_id: "proj_1",
    assigned_emp_id: "emp_4",
    assigned_emp_email: "sneha@ethara.ai",
    date_of_creation: "2026-04-02",
    date_of_assigning: "2026-04-03",
    deadline: "2026-04-10",
    status: "active",
    priority: "medium",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-04-02",
      "Task assigned to Sneha Verma on 2026-04-03",
      "Sneha Verma changed task status to in progress on 2026-04-04",
    ],
  },

  {
    id: "task_3",
    name: "Charts integration",
    description: "Integrate analytics charts",
    project_id: "proj_1",
    assigned_emp_id: "emp_3",
    assigned_emp_email: "kunal@ethara.ai",
    date_of_creation: "2026-04-04",
    date_of_assigning: "2026-04-05",
    deadline: "2026-04-14",
    status: "pending",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-04-04",
      "Task assigned to Kunal Mehta on 2026-04-05",
    ],
  },

  {
    id: "task_4",
    name: "Dark mode support",
    description: "Implement dark theme",
    project_id: "proj_1",
    assigned_emp_id: "emp_4",
    assigned_emp_email: "sneha@ethara.ai",
    date_of_creation: "2026-04-05",
    date_of_assigning: "2026-04-06",
    deadline: "2026-04-12",
    status: "completed",
    priority: "low",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-04-05",
      "Task assigned to Sneha Verma on 2026-04-06",
      "Sneha Verma changed task status to in progress on 2026-04-07",
      "Sneha Verma marked task as completed on 2026-04-09",
    ],
  },

  {
    id: "task_5",
    name: "API integration",
    description: "Connect frontend APIs",
    project_id: "proj_1",
    assigned_emp_id: "emp_3",
    assigned_emp_email: "kunal@ethara.ai",
    date_of_creation: "2026-04-07",
    date_of_assigning: "2026-04-08",
    deadline: "2026-04-18",
    status: "active",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-04-07",
      "Task assigned to Kunal Mehta on 2026-04-08",
      "Kunal Mehta changed task status to in progress on 2026-04-09",
    ],
  },

  {
    id: "task_6",
    name: "Auth middleware",
    description: "JWT auth implementation",
    project_id: "proj_2",
    assigned_emp_id: "emp_6",
    assigned_emp_email: "priya@ethara.ai",
    date_of_creation: "2026-05-01",
    date_of_assigning: "2026-05-02",
    deadline: "2026-05-12",
    status: "active",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-05-01",
      "Task assigned to Priya Nair on 2026-05-02",
      "Priya Nair changed task status to in progress on 2026-05-03",
    ],
  },

  {
    id: "task_7",
    name: "Database schema",
    description: "Design PostgreSQL schema",
    project_id: "proj_2",
    assigned_emp_id: "emp_7",
    assigned_emp_email: "rahul@ethara.ai",
    date_of_creation: "2026-05-02",
    date_of_assigning: "2026-05-03",
    deadline: "2026-05-08",
    status: "completed",
    priority: "medium",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-05-02",
      "Task assigned to Rahul Joshi on 2026-05-03",
      "Rahul Joshi changed task status to in progress on 2026-05-04",
      "Rahul Joshi marked task as completed on 2026-05-06",
    ],
  },

  {
    id: "task_8",
    name: "Payment webhook",
    description: "Stripe webhook setup",
    project_id: "proj_2",
    assigned_emp_id: "emp_8",
    assigned_emp_email: "ishita@ethara.ai",
    date_of_creation: "2026-05-02",
    date_of_assigning: "2026-05-03",
    deadline: "2026-05-16",
    status: "pending",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-05-02",
      "Task assigned to Ishita Roy on 2026-05-03",
    ],
  },

  {
    id: "task_9",
    name: "Rate limiter",
    description: "Prevent API abuse",
    project_id: "proj_2",
    assigned_emp_id: "emp_6",
    assigned_emp_email: "priya@ethara.ai",
    date_of_creation: "2026-05-04",
    date_of_assigning: "2026-05-05",
    deadline: "2026-05-15",
    status: "active",
    priority: "medium",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-05-04",
      "Task assigned to Priya Nair on 2026-05-05",
      "Priya Nair changed task status to in progress on 2026-05-06",
    ],
  },

  {
    id: "task_10",
    name: "Logging service",
    description: "Implement API logs",
    project_id: "proj_2",
    assigned_emp_id: "emp_7",
    assigned_emp_email: "rahul@ethara.ai",
    date_of_creation: "2026-05-05",
    date_of_assigning: "2026-05-06",
    deadline: "2026-05-20",
    status: "pending",
    priority: "low",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-05-05",
      "Task assigned to Rahul Joshi on 2026-05-06",
    ],
  },

  {
    id: "task_11",
    name: "Docker setup",
    description: "Containerize services",
    project_id: "proj_3",
    assigned_emp_id: "emp_10",
    assigned_emp_email: "neha@ethara.ai",
    date_of_creation: "2026-01-12",
    date_of_assigning: "2026-01-13",
    deadline: "2026-01-20",
    status: "completed",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-01-12",
      "Task assigned to Neha Arora on 2026-01-13",
      "Neha Arora changed task status to in progress on 2026-01-15",
      "Neha Arora marked task as completed on 2026-01-18",
    ],
  },

  {
    id: "task_12",
    name: "CI/CD pipeline",
    description: "Setup GitHub Actions",
    project_id: "proj_3",
    assigned_emp_id: "emp_11",
    assigned_emp_email: "kabir@ethara.ai",
    date_of_creation: "2026-01-14",
    date_of_assigning: "2026-01-15",
    deadline: "2026-01-24",
    status: "completed",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-01-14",
      "Task assigned to Kabir Khan on 2026-01-15",
      "Kabir Khan changed task status to in progress on 2026-01-17",
      "Kabir Khan marked task as completed on 2026-01-20",
    ],
  },

  {
    id: "task_13",
    name: "AWS deployment",
    description: "Deploy infrastructure",
    project_id: "proj_3",
    assigned_emp_id: "emp_12",
    assigned_emp_email: "ananya@ethara.ai",
    date_of_creation: "2026-01-16",
    date_of_assigning: "2026-01-17",
    deadline: "2026-01-28",
    status: "completed",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-01-16",
      "Task assigned to Ananya Das on 2026-01-17",
      "Ananya Das changed task status to in progress on 2026-01-18",
      "Ananya Das marked task as completed on 2026-01-25",
    ],
  },

  {
    id: "task_14",
    name: "Monitoring setup",
    description: "Add Grafana monitoring",
    project_id: "proj_3",
    assigned_emp_id: "emp_10",
    assigned_emp_email: "neha@ethara.ai",
    date_of_creation: "2026-01-18",
    date_of_assigning: "2026-01-19",
    deadline: "2026-01-26",
    status: "completed",
    priority: "medium",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-01-18",
      "Task assigned to Neha Arora on 2026-01-19",
      "Neha Arora changed task status to in progress on 2026-01-20",
      "Neha Arora marked task as completed on 2026-01-23",
    ],
  },

  {
    id: "task_15",
    name: "Login screen",
    description: "Create auth UI",
    project_id: "proj_4",
    assigned_emp_id: "emp_14",
    assigned_emp_email: "meera@ethara.ai",
    date_of_creation: "2026-02-05",
    date_of_assigning: "2026-02-06",
    deadline: "2026-02-14",
    status: "completed",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-02-05",
      "Task assigned to Meera Iyer on 2026-02-06",
      "Meera Iyer changed task status to in progress on 2026-02-07",
      "Meera Iyer marked task as completed on 2026-02-10",
    ],
  },

  {
    id: "task_16",
    name: "Cart feature",
    description: "Implement cart logic",
    project_id: "proj_4",
    assigned_emp_id: "emp_15",
    assigned_emp_email: "arjun@ethara.ai",
    date_of_creation: "2026-02-06",
    date_of_assigning: "2026-02-07",
    deadline: "2026-04-20",
    status: "overdue",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-02-06",
      "Task assigned to Arjun Rao on 2026-02-07",
      "Arjun Rao changed task status to in progress on 2026-02-09",
      "Task deadline exceeded on 2026-04-20",
    ],
  },

  {
    id: "task_17",
    name: "Push notifications",
    description: "Integrate Firebase push",
    project_id: "proj_4",
    assigned_emp_id: "emp_16",
    assigned_emp_email: "pooja@ethara.ai",
    date_of_creation: "2026-02-08",
    date_of_assigning: "2026-02-09",
    deadline: "2026-02-20",
    status: "active",
    priority: "medium",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-02-08",
      "Task assigned to Pooja Mishra on 2026-02-09",
      "Pooja Mishra changed task status to in progress on 2026-02-11",
    ],
  },

  {
    id: "task_18",
    name: "Payment integration",
    description: "UPI payment support",
    project_id: "proj_4",
    assigned_emp_id: "emp_14",
    assigned_emp_email: "meera@ethara.ai",
    date_of_creation: "2026-02-10",
    date_of_assigning: "2026-02-11",
    deadline: "2026-02-25",
    status: "pending",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-02-10",
      "Task assigned to Meera Iyer on 2026-02-11",
    ],
  },

  {
    id: "task_19",
    name: "App optimization",
    description: "Improve performance",
    project_id: "proj_4",
    assigned_emp_id: "emp_15",
    assigned_emp_email: "arjun@ethara.ai",
    date_of_creation: "2026-02-12",
    date_of_assigning: "2026-02-13",
    deadline: "2026-04-20",
    status: "overdue",
    priority: "medium",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-02-12",
      "Task assigned to Arjun Rao on 2026-02-13",
      "Arjun Rao changed task status to in progress on 2026-02-15",
      "Task deadline exceeded on 2026-04-20",
    ],
  },

  {
    id: "task_20",
    name: "Research AI models",
    description: "Explore LLM architectures",
    project_id: "proj_5",
    assigned_emp_id: null,
    assigned_emp_email: null,
    date_of_creation: "2026-05-08",
    date_of_assigning: null,
    deadline: "2026-06-15",
    status: "pending",
    priority: "high",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-05-08",
    ],
  },

  {
    id: "task_21",
    name: "Dataset collection",
    description: "Gather training datasets",
    project_id: "proj_5",
    assigned_emp_id: null,
    assigned_emp_email: null,
    date_of_creation: "2026-05-09",
    date_of_assigning: null,
    deadline: "2026-06-20",
    status: "pending",
    priority: "medium",
    activity_logs: [
      "Task created by Aarav Sharma on 2026-05-09",
    ],
  },
];